package com.firstbbs.dao;

import com.firstbbs.model.Board;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    int insertSelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    Board selectByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Board record);
}