package com.firstbbs.model;

import java.io.Serializable;

public class Board implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.board_id
     *
     * @mbggenerated
     */
    private Integer boardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.board_name
     *
     * @mbggenerated
     */
    private String boardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.board_desc
     *
     * @mbggenerated
     */
    private String boardDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.board_post_num
     *
     * @mbggenerated
     */
    private Integer boardPostNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_board
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board.board_id
     *
     * @return the value of t_board.board_id
     *
     * @mbggenerated
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board.board_id
     *
     * @param boardId the value for t_board.board_id
     *
     * @mbggenerated
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board.board_name
     *
     * @return the value of t_board.board_name
     *
     * @mbggenerated
     */
    public String getBoardName() {
        return boardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board.board_name
     *
     * @param boardName the value for t_board.board_name
     *
     * @mbggenerated
     */
    public void setBoardName(String boardName) {
        this.boardName = boardName == null ? null : boardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board.board_desc
     *
     * @return the value of t_board.board_desc
     *
     * @mbggenerated
     */
    public String getBoardDesc() {
        return boardDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board.board_desc
     *
     * @param boardDesc the value for t_board.board_desc
     *
     * @mbggenerated
     */
    public void setBoardDesc(String boardDesc) {
        this.boardDesc = boardDesc == null ? null : boardDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board.board_post_num
     *
     * @return the value of t_board.board_post_num
     *
     * @mbggenerated
     */
    public Integer getBoardPostNum() {
        return boardPostNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board.board_post_num
     *
     * @param boardPostNum the value for t_board.board_post_num
     *
     * @mbggenerated
     */
    public void setBoardPostNum(Integer boardPostNum) {
        this.boardPostNum = boardPostNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Board other = (Board) that;
        return (this.getBoardId() == null ? other.getBoardId() == null : this.getBoardId().equals(other.getBoardId()))
            && (this.getBoardName() == null ? other.getBoardName() == null : this.getBoardName().equals(other.getBoardName()))
            && (this.getBoardDesc() == null ? other.getBoardDesc() == null : this.getBoardDesc().equals(other.getBoardDesc()))
            && (this.getBoardPostNum() == null ? other.getBoardPostNum() == null : this.getBoardPostNum().equals(other.getBoardPostNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBoardId() == null) ? 0 : getBoardId().hashCode());
        result = prime * result + ((getBoardName() == null) ? 0 : getBoardName().hashCode());
        result = prime * result + ((getBoardDesc() == null) ? 0 : getBoardDesc().hashCode());
        result = prime * result + ((getBoardPostNum() == null) ? 0 : getBoardPostNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", boardId=").append(boardId);
        sb.append(", boardName=").append(boardName);
        sb.append(", boardDesc=").append(boardDesc);
        sb.append(", boardPostNum=").append(boardPostNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}