package com.firstbbs.model;

import java.io.Serializable;
import java.util.Date;

public class Post implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_id
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_board_id
     *
     * @mbggenerated
     */
    private Integer postBoardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_user_name
     *
     * @mbggenerated
     */
    private String postUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_title
     *
     * @mbggenerated
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_good_count
     *
     * @mbggenerated
     */
    private Integer postGoodCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_bad_count
     *
     * @mbggenerated
     */
    private Integer postBadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_view_count
     *
     * @mbggenerated
     */
    private Integer postViewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_reply_count
     *
     * @mbggenerated
     */
    private Integer postReplyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_status
     *
     * @mbggenerated
     */
    private Integer postStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_create_time
     *
     * @mbggenerated
     */
    private Date postCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_update_time
     *
     * @mbggenerated
     */
    private Date postUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_content
     *
     * @mbggenerated
     */
    private String postContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_post
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_id
     *
     * @return the value of t_post.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_id
     *
     * @param postId the value for t_post.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_board_id
     *
     * @return the value of t_post.post_board_id
     *
     * @mbggenerated
     */
    public Integer getPostBoardId() {
        return postBoardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_board_id
     *
     * @param postBoardId the value for t_post.post_board_id
     *
     * @mbggenerated
     */
    public void setPostBoardId(Integer postBoardId) {
        this.postBoardId = postBoardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_user_name
     *
     * @return the value of t_post.post_user_name
     *
     * @mbggenerated
     */
    public String getPostUserName() {
        return postUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_user_name
     *
     * @param postUserName the value for t_post.post_user_name
     *
     * @mbggenerated
     */
    public void setPostUserName(String postUserName) {
        this.postUserName = postUserName == null ? null : postUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_title
     *
     * @return the value of t_post.post_title
     *
     * @mbggenerated
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_title
     *
     * @param postTitle the value for t_post.post_title
     *
     * @mbggenerated
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_good_count
     *
     * @return the value of t_post.post_good_count
     *
     * @mbggenerated
     */
    public Integer getPostGoodCount() {
        return postGoodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_good_count
     *
     * @param postGoodCount the value for t_post.post_good_count
     *
     * @mbggenerated
     */
    public void setPostGoodCount(Integer postGoodCount) {
        this.postGoodCount = postGoodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_bad_count
     *
     * @return the value of t_post.post_bad_count
     *
     * @mbggenerated
     */
    public Integer getPostBadCount() {
        return postBadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_bad_count
     *
     * @param postBadCount the value for t_post.post_bad_count
     *
     * @mbggenerated
     */
    public void setPostBadCount(Integer postBadCount) {
        this.postBadCount = postBadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_view_count
     *
     * @return the value of t_post.post_view_count
     *
     * @mbggenerated
     */
    public Integer getPostViewCount() {
        return postViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_view_count
     *
     * @param postViewCount the value for t_post.post_view_count
     *
     * @mbggenerated
     */
    public void setPostViewCount(Integer postViewCount) {
        this.postViewCount = postViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_reply_count
     *
     * @return the value of t_post.post_reply_count
     *
     * @mbggenerated
     */
    public Integer getPostReplyCount() {
        return postReplyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_reply_count
     *
     * @param postReplyCount the value for t_post.post_reply_count
     *
     * @mbggenerated
     */
    public void setPostReplyCount(Integer postReplyCount) {
        this.postReplyCount = postReplyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_status
     *
     * @return the value of t_post.post_status
     *
     * @mbggenerated
     */
    public Integer getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_status
     *
     * @param postStatus the value for t_post.post_status
     *
     * @mbggenerated
     */
    public void setPostStatus(Integer postStatus) {
        this.postStatus = postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_create_time
     *
     * @return the value of t_post.post_create_time
     *
     * @mbggenerated
     */
    public Date getPostCreateTime() {
        return postCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_create_time
     *
     * @param postCreateTime the value for t_post.post_create_time
     *
     * @mbggenerated
     */
    public void setPostCreateTime(Date postCreateTime) {
        this.postCreateTime = postCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_update_time
     *
     * @return the value of t_post.post_update_time
     *
     * @mbggenerated
     */
    public Date getPostUpdateTime() {
        return postUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_update_time
     *
     * @param postUpdateTime the value for t_post.post_update_time
     *
     * @mbggenerated
     */
    public void setPostUpdateTime(Date postUpdateTime) {
        this.postUpdateTime = postUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_content
     *
     * @return the value of t_post.post_content
     *
     * @mbggenerated
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_content
     *
     * @param postContent the value for t_post.post_content
     *
     * @mbggenerated
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Post other = (Post) that;
        return (this.getPostId() == null ? other.getPostId() == null : this.getPostId().equals(other.getPostId()))
            && (this.getPostBoardId() == null ? other.getPostBoardId() == null : this.getPostBoardId().equals(other.getPostBoardId()))
            && (this.getPostUserName() == null ? other.getPostUserName() == null : this.getPostUserName().equals(other.getPostUserName()))
            && (this.getPostTitle() == null ? other.getPostTitle() == null : this.getPostTitle().equals(other.getPostTitle()))
            && (this.getPostGoodCount() == null ? other.getPostGoodCount() == null : this.getPostGoodCount().equals(other.getPostGoodCount()))
            && (this.getPostBadCount() == null ? other.getPostBadCount() == null : this.getPostBadCount().equals(other.getPostBadCount()))
            && (this.getPostViewCount() == null ? other.getPostViewCount() == null : this.getPostViewCount().equals(other.getPostViewCount()))
            && (this.getPostReplyCount() == null ? other.getPostReplyCount() == null : this.getPostReplyCount().equals(other.getPostReplyCount()))
            && (this.getPostStatus() == null ? other.getPostStatus() == null : this.getPostStatus().equals(other.getPostStatus()))
            && (this.getPostCreateTime() == null ? other.getPostCreateTime() == null : this.getPostCreateTime().equals(other.getPostCreateTime()))
            && (this.getPostUpdateTime() == null ? other.getPostUpdateTime() == null : this.getPostUpdateTime().equals(other.getPostUpdateTime()))
            && (this.getPostContent() == null ? other.getPostContent() == null : this.getPostContent().equals(other.getPostContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPostId() == null) ? 0 : getPostId().hashCode());
        result = prime * result + ((getPostBoardId() == null) ? 0 : getPostBoardId().hashCode());
        result = prime * result + ((getPostUserName() == null) ? 0 : getPostUserName().hashCode());
        result = prime * result + ((getPostTitle() == null) ? 0 : getPostTitle().hashCode());
        result = prime * result + ((getPostGoodCount() == null) ? 0 : getPostGoodCount().hashCode());
        result = prime * result + ((getPostBadCount() == null) ? 0 : getPostBadCount().hashCode());
        result = prime * result + ((getPostViewCount() == null) ? 0 : getPostViewCount().hashCode());
        result = prime * result + ((getPostReplyCount() == null) ? 0 : getPostReplyCount().hashCode());
        result = prime * result + ((getPostStatus() == null) ? 0 : getPostStatus().hashCode());
        result = prime * result + ((getPostCreateTime() == null) ? 0 : getPostCreateTime().hashCode());
        result = prime * result + ((getPostUpdateTime() == null) ? 0 : getPostUpdateTime().hashCode());
        result = prime * result + ((getPostContent() == null) ? 0 : getPostContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", postId=").append(postId);
        sb.append(", postBoardId=").append(postBoardId);
        sb.append(", postUserName=").append(postUserName);
        sb.append(", postTitle=").append(postTitle);
        sb.append(", postGoodCount=").append(postGoodCount);
        sb.append(", postBadCount=").append(postBadCount);
        sb.append(", postViewCount=").append(postViewCount);
        sb.append(", postReplyCount=").append(postReplyCount);
        sb.append(", postStatus=").append(postStatus);
        sb.append(", postCreateTime=").append(postCreateTime);
        sb.append(", postUpdateTime=").append(postUpdateTime);
        sb.append(", postContent=").append(postContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}