package com.firstbbs.model;

import java.io.Serializable;
import java.util.Date;

public class Reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_id
     *
     * @mbggenerated
     */
    private Integer replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_post_id
     *
     * @mbggenerated
     */
    private Integer replyPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_user_name
     *
     * @mbggenerated
     */
    private String replyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_good_count
     *
     * @mbggenerated
     */
    private Integer replyGoodCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_bad_count
     *
     * @mbggenerated
     */
    private Integer replyBadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_create_time
     *
     * @mbggenerated
     */
    private Date replyCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_content
     *
     * @mbggenerated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_id
     *
     * @return the value of t_reply.reply_id
     *
     * @mbggenerated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_id
     *
     * @param replyId the value for t_reply.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_post_id
     *
     * @return the value of t_reply.reply_post_id
     *
     * @mbggenerated
     */
    public Integer getReplyPostId() {
        return replyPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_post_id
     *
     * @param replyPostId the value for t_reply.reply_post_id
     *
     * @mbggenerated
     */
    public void setReplyPostId(Integer replyPostId) {
        this.replyPostId = replyPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_user_name
     *
     * @return the value of t_reply.reply_user_name
     *
     * @mbggenerated
     */
    public String getReplyUserName() {
        return replyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_user_name
     *
     * @param replyUserName the value for t_reply.reply_user_name
     *
     * @mbggenerated
     */
    public void setReplyUserName(String replyUserName) {
        this.replyUserName = replyUserName == null ? null : replyUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_good_count
     *
     * @return the value of t_reply.reply_good_count
     *
     * @mbggenerated
     */
    public Integer getReplyGoodCount() {
        return replyGoodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_good_count
     *
     * @param replyGoodCount the value for t_reply.reply_good_count
     *
     * @mbggenerated
     */
    public void setReplyGoodCount(Integer replyGoodCount) {
        this.replyGoodCount = replyGoodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_bad_count
     *
     * @return the value of t_reply.reply_bad_count
     *
     * @mbggenerated
     */
    public Integer getReplyBadCount() {
        return replyBadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_bad_count
     *
     * @param replyBadCount the value for t_reply.reply_bad_count
     *
     * @mbggenerated
     */
    public void setReplyBadCount(Integer replyBadCount) {
        this.replyBadCount = replyBadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_create_time
     *
     * @return the value of t_reply.reply_create_time
     *
     * @mbggenerated
     */
    public Date getReplyCreateTime() {
        return replyCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_create_time
     *
     * @param replyCreateTime the value for t_reply.reply_create_time
     *
     * @mbggenerated
     */
    public void setReplyCreateTime(Date replyCreateTime) {
        this.replyCreateTime = replyCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_content
     *
     * @return the value of t_reply.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_content
     *
     * @param replyContent the value for t_reply.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reply other = (Reply) that;
        return (this.getReplyId() == null ? other.getReplyId() == null : this.getReplyId().equals(other.getReplyId()))
            && (this.getReplyPostId() == null ? other.getReplyPostId() == null : this.getReplyPostId().equals(other.getReplyPostId()))
            && (this.getReplyUserName() == null ? other.getReplyUserName() == null : this.getReplyUserName().equals(other.getReplyUserName()))
            && (this.getReplyGoodCount() == null ? other.getReplyGoodCount() == null : this.getReplyGoodCount().equals(other.getReplyGoodCount()))
            && (this.getReplyBadCount() == null ? other.getReplyBadCount() == null : this.getReplyBadCount().equals(other.getReplyBadCount()))
            && (this.getReplyCreateTime() == null ? other.getReplyCreateTime() == null : this.getReplyCreateTime().equals(other.getReplyCreateTime()))
            && (this.getReplyContent() == null ? other.getReplyContent() == null : this.getReplyContent().equals(other.getReplyContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getReplyId() == null) ? 0 : getReplyId().hashCode());
        result = prime * result + ((getReplyPostId() == null) ? 0 : getReplyPostId().hashCode());
        result = prime * result + ((getReplyUserName() == null) ? 0 : getReplyUserName().hashCode());
        result = prime * result + ((getReplyGoodCount() == null) ? 0 : getReplyGoodCount().hashCode());
        result = prime * result + ((getReplyBadCount() == null) ? 0 : getReplyBadCount().hashCode());
        result = prime * result + ((getReplyCreateTime() == null) ? 0 : getReplyCreateTime().hashCode());
        result = prime * result + ((getReplyContent() == null) ? 0 : getReplyContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", replyId=").append(replyId);
        sb.append(", replyPostId=").append(replyPostId);
        sb.append(", replyUserName=").append(replyUserName);
        sb.append(", replyGoodCount=").append(replyGoodCount);
        sb.append(", replyBadCount=").append(replyBadCount);
        sb.append(", replyCreateTime=").append(replyCreateTime);
        sb.append(", replyContent=").append(replyContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}